package server

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"math"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"sync"
	"time"

	"sentinel-linux/internal/detect"
	"sentinel-linux/internal/store"
)

const (
	motionQuiet     = 30 * time.Second // quiet gap that ends a motion episode
	motionRepeat    = 60 * time.Second // during sustained motion, one event per minute
	alarmMergeWin   = 60 * time.Second // Mac rule: detections within 60 s group into one alarm
	offlineAfter    = 60 * time.Second
	eventsRetention = 30 * 24 * time.Hour
)

// detectState tracks motion episodes and camera health between callbacks.
type detectState struct {
	mu          sync.Mutex
	lastMotion  map[string]time.Time
	lastEvent   map[string]time.Time
	lastReady   map[string]time.Time
	offlineOpen map[string]string    // camera → open Camera Offline alarm id
	vehicles    map[string][]seenBox // recently seen vehicle boxes (parked-car filter)
}

func (s *Server) eventsDir() string   { return filepath.Join(s.Store.DataDir(), "events") }
func (s *Server) evidenceDir() string { return filepath.Join(s.Store.DataDir(), "evidence") }

// detectionSources builds the motion-reader list from the camera table. Each
// reader pulls the low-res live path from the local MediaMTX.
func (s *Server) detectionSources(cams []store.Camera) []detect.Source {
	var out []detect.Source
	for _, c := range cams {
		if c.MotionLevel <= 0 {
			continue
		}
		out = append(out, detect.Source{
			CameraID: c.ID,
			URL:      fmt.Sprintf("rtsp://127.0.0.1:%d/%s", s.Media.Ports.RTSP, s.Media.LivePath(c.ID)),
			Level:    c.MotionLevel,
			Objects:  s.Detect != nil && s.Detect.Objects != nil,
		})
	}
	return out
}

// OnMotion is the detector callback. It turns raw over-threshold frames into
// at most one event per episode (plus one per minute of sustained motion),
// each with a snapshot, and raises/merges the camera's Motion alarm.
func (s *Server) OnMotion(m detect.Motion) {
	st := &s.detect
	st.mu.Lock()
	if st.lastMotion == nil {
		st.lastMotion, st.lastEvent = map[string]time.Time{}, map[string]time.Time{}
	}
	prevMotion, prevEvent := st.lastMotion[m.CameraID], st.lastEvent[m.CameraID]
	st.lastMotion[m.CameraID] = m.At
	newEpisode := m.At.Sub(prevMotion) >= motionQuiet
	due := m.At.Sub(prevEvent) >= motionRepeat
	if !newEpisode && !due {
		st.mu.Unlock()
		return
	}
	st.lastEvent[m.CameraID] = m.At
	st.mu.Unlock()

	// Mac rule: detections less than 60 s apart belong to one alarm. Motion
	// that never stopped always continues the alarm of its previous event;
	// a new episode joins it only if it started within 60 s of the last motion.
	mergeSince := m.At.Add(time.Second) // matches nothing → new alarm
	if !prevEvent.IsZero() && (!newEpisode || m.At.Sub(prevMotion) < alarmMergeWin) {
		mergeSince = prevEvent
	}

	ctx := s.Ctx
	cam, err := s.Store.Camera(ctx, m.CameraID)
	if err != nil {
		return
	}
	ev := &store.Event{CameraID: cam.ID, Kind: "Motion", Score: m.Score, CreatedAt: m.At.Unix()}
	if err := s.Store.AddEvent(ctx, ev); err != nil {
		slog.Error("save motion event", "err", err)
		return
	}
	if s.alertMode(cam) != alertMotion {
		// People/vehicle modes: motion is logged as an event, but only a
		// detection raises an alarm.
		s.motionSnapshot(cam, ev)
		return
	}
	alarm, isNew, err := s.Store.RaiseAlarm(ctx, store.AlarmInput{
		CameraID: cam.ID, CameraName: cam.Name, Kind: "Motion", Title: "Motion detected", Severity: "Warning",
		Detail:  fmt.Sprintf("%s detected motion at %s.", cam.Name, m.At.Format("3:04:05 PM")),
		EventID: ev.ID, At: m.At, MergeSince: mergeSince, Origin: "Automatically generated by video analytics",
	})
	if err == nil {
		_ = s.Store.SetEventAlarm(ctx, ev.ID, alarm.ID)
		if isNew {
			slog.Info("motion alarm", "camera", cam.Name, "score", fmt.Sprintf("%.3f", m.Score))
		}
	}
	s.motionSnapshot(cam, ev)
}

// motionSnapshot grabs the event thumbnail in the background (~1-2 s).
func (s *Server) motionSnapshot(cam *store.Camera, ev *store.Event) {
	if !s.Detect.Available() {
		return
	}
	go func() {
		if err := os.MkdirAll(s.eventsDir(), 0o750); err != nil {
			return
		}
		name := ev.ID + ".jpg"
		url := fmt.Sprintf("rtsp://127.0.0.1:%d/%s", s.Media.Ports.RTSP, s.Media.LivePath(cam.ID))
		if err := s.Detect.Snapshot(s.Ctx, url, filepath.Join(s.eventsDir(), name)); err == nil {
			_ = s.Store.SetEventThumbnail(s.Ctx, ev.ID, name)
		}
	}()
}

// RunMonitors raises Camera Offline alarms and prunes old events until ctx ends.
func (s *Server) RunMonitors(ctx context.Context) {
	tick := time.NewTicker(15 * time.Second)
	defer tick.Stop()
	lastPrune := time.Time{}
	for {
		select {
		case <-ctx.Done():
			return
		case <-tick.C:
		}
		s.checkCameraHealth(ctx)
		if time.Since(lastPrune) > time.Hour {
			lastPrune = time.Now()
			files, err := s.Store.PruneEvents(ctx, time.Now().Add(-eventsRetention))
			if err == nil {
				for _, f := range files {
					_ = os.Remove(filepath.Join(s.eventsDir(), filepath.Base(f)))
				}
			}
		}
	}
}

func (s *Server) checkCameraHealth(ctx context.Context) {
	running, _ := s.Media.Status()
	if !running {
		return
	}
	cams, err := s.Store.Cameras(ctx)
	if err != nil {
		return
	}
	st := &s.detect
	st.mu.Lock()
	if st.lastReady == nil {
		st.lastReady, st.offlineOpen = map[string]time.Time{}, map[string]string{}
	}
	st.mu.Unlock()
	now := time.Now()
	for _, c := range cams {
		ready := s.Media.State(c.ID).Ready
		st.mu.Lock()
		last, seen := st.lastReady[c.ID]
		open := st.offlineOpen[c.ID]
		if ready {
			st.lastReady[c.ID] = now
			delete(st.offlineOpen, c.ID)
		}
		st.mu.Unlock()
		switch {
		case ready && open != "":
			_ = s.Store.AddAlarmNote(ctx, open, "Video restored")
		case !ready && seen && open == "" && now.Sub(last) >= offlineAfter:
			a, _, err := s.Store.RaiseAlarm(ctx, store.AlarmInput{
				CameraID: c.ID, CameraName: c.Name, Kind: "Camera Offline", Title: "Camera offline", Severity: "Critical",
				Detail: fmt.Sprintf("%s stopped delivering video at %s.", c.Name, last.Format("3:04 PM")),
				At:     now, Origin: "Automatically generated by stream supervisor",
			})
			if err == nil {
				st.mu.Lock()
				st.offlineOpen[c.ID] = a.ID
				st.mu.Unlock()
				slog.Warn("camera offline", "camera", c.Name)
			}
		}
	}
}

// segmentAt finds the recording that covers t (with a little slack).
func (s *Server) segmentAt(cameraID string, t int64) *segment {
	segs, err := s.listSegments(cameraID)
	if err != nil {
		return nil
	}
	for i := range segs {
		if segs[i].Start-2 <= t && t <= segs[i].End+5 {
			return &segs[i]
		}
	}
	return nil
}

var (
	errNoClip       = errors.New("No recording is linked to this alarm yet, or it has already been cleaned up.")
	errClipWriting  = errors.New("The recording for this alarm is still being written. Try again in a minute.")
	errNotRecording = errors.New("This alarm has no recording to lock.")
)

// lockEvidence copies the alarm's recording into the evidence vault (outside
// the retention-managed recordings directory), hashes it and makes it
// read-only. Idempotent: a retry returns the clip already locked.
func (s *Server) lockEvidence(ctx context.Context, a *store.Alarm, who string) (*store.Evidence, error) {
	if ev, err := s.Store.EvidenceForAlarm(ctx, a.ID); err == nil {
		return ev, nil
	}
	if a.CameraID == "" || a.Kind == "Camera Offline" {
		return nil, errNotRecording
	}
	seg := s.segmentAt(a.CameraID, a.CreatedAt)
	if seg == nil {
		return nil, errNoClip
	}
	if err := os.MkdirAll(s.evidenceDir(), 0o750); err != nil {
		return nil, err
	}
	caseID := s.Store.NextCaseID(ctx, time.Now())
	dst := filepath.Join(s.evidenceDir(), caseID+".mp4")
	// A segment still being recorded (they run 15 min) is copied up to its
	// last complete MP4 box, so the alarm can be preserved right away.
	size, sum, err := copyHashed(filepath.Join(s.recordingsRoot(), a.CameraID, seg.Name), dst, seg.Writing)
	if err != nil {
		return nil, err
	}
	if size == 0 {
		_ = os.Remove(dst)
		return nil, errClipWriting
	}
	_ = os.Chmod(dst, 0o440)
	start, end := time.Unix(seg.Start, 0), time.Unix(seg.End, 0)
	rangeLabel := start.Format("Jan 2 15:04:05") + " – " + end.Format("15:04:05")
	if seg.Writing {
		rangeLabel = start.Format("Jan 2 15:04:05") + " – " + time.Now().Format("15:04:05") + " (recording in progress)"
	}
	ev := &store.Evidence{
		ID: store.NewID(), CaseID: caseID, AlarmID: a.ID, CameraID: a.CameraID, CameraName: a.CameraName,
		Title: "Recorded Segment Export", Range: rangeLabel,
		File: filepath.Base(dst), Size: size, SHA256: sum, LockedAt: time.Now().Unix(), LockedBy: who,
	}
	if err := s.Store.AddEvidence(ctx, ev); err != nil {
		_ = os.Remove(dst)
		return nil, err
	}
	_ = s.Store.AddAlarmNote(ctx, a.ID, "Evidence "+caseID+" locked by "+who)
	_ = s.Store.Audit(ctx, who, "Evidence", "Locked evidence", caseID+" for alarm "+a.Title+" ("+a.CameraName+"), sha256 "+sum[:16]+"…")
	return ev, nil
}

func copyHashed(src, dst string, completeBoxesOnly bool) (int64, string, error) {
	in, err := os.Open(src)
	if err != nil {
		return 0, "", err
	}
	defer in.Close()
	var r io.Reader = in
	if completeBoxesOnly {
		info, err := in.Stat()
		if err != nil {
			return 0, "", err
		}
		n, err := completeMP4Prefix(in, info.Size())
		if err != nil {
			return 0, "", err
		}
		if _, err := in.Seek(0, io.SeekStart); err != nil {
			return 0, "", err
		}
		r = io.LimitReader(in, n)
	}
	out, err := os.OpenFile(dst, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o640)
	if err != nil {
		return 0, "", err
	}
	h := sha256.New()
	n, err := io.Copy(io.MultiWriter(out, h), r)
	if cerr := out.Close(); err == nil {
		err = cerr
	}
	if err != nil {
		_ = os.Remove(dst)
		return 0, "", err
	}
	return n, hex.EncodeToString(h.Sum(nil)), nil
}

// completeMP4Prefix returns the length of the file made of whole top-level
// MP4 boxes (size+type headers), dropping a fragment that's half written.
func completeMP4Prefix(f io.ReadSeeker, fileSize int64) (int64, error) {
	var off int64
	hdr := make([]byte, 16)
	for off+8 <= fileSize {
		if _, err := f.Seek(off, io.SeekStart); err != nil {
			return 0, err
		}
		if _, err := io.ReadFull(f, hdr[:8]); err != nil {
			return off, nil
		}
		size := int64(uint32(hdr[0])<<24 | uint32(hdr[1])<<16 | uint32(hdr[2])<<8 | uint32(hdr[3]))
		switch size {
		case 0: // box runs to end of file — still open
			return off, nil
		case 1: // 64-bit size follows the type
			if _, err := io.ReadFull(f, hdr[8:16]); err != nil {
				return off, nil
			}
			size = 0
			for _, b := range hdr[8:16] {
				size = size<<8 | int64(b)
			}
		}
		if size < 8 || off+size > fileSize {
			return off, nil
		}
		off += size
	}
	return off, nil
}

// MARK: - Phone payloads (Mac SentinelHTTPBridge shapes)

func (s *Server) phoneAlarm(ctx context.Context, a *store.Alarm) map[string]any {
	hasClip := false
	if a.CameraID != "" && a.Kind != "Camera Offline" {
		hasClip = s.segmentAt(a.CameraID, a.CreatedAt) != nil
	}
	out := map[string]any{
		"id": a.ID, "title": a.Title, "detail": a.Detail, "severity": a.Severity, "state": a.State,
		"createdAt": a.CreatedAt, "lastEventAt": a.LastEventAt, "kind": a.Kind, "owner": a.Owner,
		"eventCount": a.EventCount, "source": a.CameraName, "hasClip": hasClip, "instructions": []any{},
	}
	if a.CameraID != "" {
		out["cameraID"] = a.CameraID
		out["cameraName"] = a.CameraName
	}
	if ev, err := s.Store.EvidenceForAlarm(ctx, a.ID); err == nil {
		out["evidence"] = phoneEvidence(ev)
	}
	return out
}

func phoneEvidence(e *store.Evidence) map[string]any {
	out := map[string]any{
		"id": e.ID, "caseID": e.CaseID, "title": e.Title, "camera": e.CameraName, "range": e.Range,
		"status": "Locked", "isLocked": true, "lockedAt": e.LockedAt, "sha256": e.SHA256, "lockedBy": e.LockedBy,
	}
	if e.AlarmID != "" {
		out["alertID"] = e.AlarmID
	}
	return out
}

// motionConfidence maps a motion score to the phone's "confidence" percent:
// 70% at the medium threshold, approaching 99% as more of the picture moves.
func motionConfidence(score float64) float64 {
	c := 0.6 + 0.4*math.Min(1, score/(4*detect.Thresholds[2]))
	return math.Min(0.99, math.Round(c*100)/100)
}

func (s *Server) handlePhoneAlerts(w http.ResponseWriter, r *http.Request, _ *store.PairedDevice) {
	alarms, err := s.Store.Alarms(r.Context(), true, 200)
	if err != nil {
		writeError(w, http.StatusServiceUnavailable, "server busy, try again")
		return
	}
	out := make([]map[string]any, 0, len(alarms))
	for i := range alarms {
		out = append(out, s.phoneAlarm(r.Context(), &alarms[i]))
	}
	writeJSON(w, http.StatusOK, out)
}

func (s *Server) handlePhoneAlarmAction(w http.ResponseWriter, r *http.Request, dev *store.PairedDevice) {
	action := r.PathValue("action")
	if action != "acknowledge" && action != "lock-evidence" {
		writeError(w, http.StatusNotFound, "not found")
		return
	}
	a, err := s.Store.Alarm(r.Context(), r.PathValue("id"))
	if err != nil {
		writeError(w, http.StatusNotFound, "Alarm not found — it may have been cleared on the server.")
		return
	}
	who := dev.Name + " (iPhone)"
	if action == "acknowledge" {
		if !store.IsOpenState(a.State) {
			writeError(w, http.StatusConflict, "This alarm was already "+lower(a.State)+" on the server.")
			return
		}
		// Only New/Snoozed move to Acknowledged; an alarm someone is
		// investigating isn't downgraded. Either way, return its state.
		if a.State == "New" || a.State == "Snoozed" {
			if a, err = s.Store.SetAlarmState(r.Context(), a.ID, "Acknowledged", who, "Acknowledged from "+who); err != nil {
				writeError(w, http.StatusServiceUnavailable, "server busy, try again")
				return
			}
			_ = s.Store.Audit(r.Context(), who, "Alarms", "Acknowledged alarm", a.Title+" ("+a.CameraName+")")
		}
		writeJSON(w, http.StatusOK, s.phoneAlarm(r.Context(), a))
		return
	}
	ev, err := s.lockEvidence(r.Context(), a, who)
	if err != nil {
		writeError(w, http.StatusConflict, err.Error())
		return
	}
	writeJSON(w, http.StatusOK, phoneEvidence(ev))
}

func (s *Server) handlePhoneEvents(w http.ResponseWriter, r *http.Request, _ *store.PairedDevice) {
	events, err := s.Store.Events(r.Context(), "", 200)
	if err != nil {
		writeError(w, http.StatusServiceUnavailable, "server busy, try again")
		return
	}
	names := s.cameraNames(r.Context())
	out := make([]map[string]any, 0, len(events))
	for _, e := range events {
		name := names[e.CameraID]
		if name == "" {
			name = "Camera"
		}
		conf := e.Score
		if e.Kind == "Motion" {
			conf = motionConfidence(e.Score)
		}
		item := map[string]any{
			"id": e.ID, "cameraID": e.CameraID, "cameraName": name, "kind": e.Kind,
			"confidence": conf, "createdAt": e.CreatedAt, "hasThumbnail": e.HasThumb,
		}
		if e.Description != "" {
			item["description"] = e.Description
		}
		out = append(out, item)
	}
	writeJSON(w, http.StatusOK, out)
}

func (s *Server) cameraNames(ctx context.Context) map[string]string {
	names := map[string]string{}
	if cams, err := s.Store.Cameras(ctx); err == nil {
		for _, c := range cams {
			names[c.ID] = c.Name
		}
	}
	return names
}

func (s *Server) serveEventThumbnail(w http.ResponseWriter, r *http.Request, id string) {
	e, err := s.Store.Event(r.Context(), id)
	if err != nil || e.Thumbnail == "" {
		writeError(w, http.StatusNotFound, "no thumbnail")
		return
	}
	f, err := os.Open(filepath.Join(s.eventsDir(), filepath.Base(e.Thumbnail)))
	if err != nil {
		writeError(w, http.StatusNotFound, "no thumbnail")
		return
	}
	defer f.Close()
	info, _ := f.Stat()
	w.Header().Set("Content-Type", "image/jpeg")
	w.Header().Set("Cache-Control", "private, max-age=86400")
	http.ServeContent(w, r, "thumbnail.jpg", info.ModTime(), f)
}

// MARK: - Dashboard API

func (s *Server) handleListAlarms(w http.ResponseWriter, r *http.Request) {
	openOnly := r.URL.Query().Get("state") != "all"
	alarms, err := s.Store.Alarms(r.Context(), openOnly, 500)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	type view struct {
		store.Alarm
		HasClip  bool            `json:"hasClip"`
		Evidence *store.Evidence `json:"evidence,omitempty"`
	}
	out := make([]view, 0, len(alarms))
	for _, a := range alarms {
		v := view{Alarm: a}
		if a.CameraID != "" && a.Kind != "Camera Offline" {
			v.HasClip = s.segmentAt(a.CameraID, a.CreatedAt) != nil
		}
		if ev, err := s.Store.EvidenceForAlarm(r.Context(), a.ID); err == nil {
			v.Evidence = ev
		}
		out = append(out, v)
	}
	writeJSON(w, http.StatusOK, out)
}

func (s *Server) handleSetAlarmState(w http.ResponseWriter, r *http.Request) {
	var in struct {
		State string `json:"state"`
		Note  string `json:"note"`
	}
	if !readJSON(w, r, &in) {
		return
	}
	if !store.ValidAlarmState(in.State) {
		writeError(w, http.StatusBadRequest, "unknown alarm state")
		return
	}
	u := currentUser(r)
	note := in.State + " by " + u.Name
	if in.Note != "" {
		note += ": " + in.Note
	}
	a, err := s.Store.SetAlarmState(r.Context(), r.PathValue("id"), in.State, u.Name, note)
	if errors.Is(err, store.ErrNotFound) {
		writeError(w, http.StatusNotFound, "alarm not found")
		return
	} else if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	s.audit(r, "Alarms", "Set alarm "+lower(in.State), a.Title+" ("+a.CameraName+")")
	writeJSON(w, http.StatusOK, a)
}

func (s *Server) handleLockEvidence(w http.ResponseWriter, r *http.Request) {
	a, err := s.Store.Alarm(r.Context(), r.PathValue("id"))
	if err != nil {
		writeError(w, http.StatusNotFound, "alarm not found")
		return
	}
	ev, err := s.lockEvidence(r.Context(), a, currentUser(r).Name)
	if err != nil {
		writeError(w, http.StatusConflict, err.Error())
		return
	}
	writeJSON(w, http.StatusOK, ev)
}

func (s *Server) handleListEvents(w http.ResponseWriter, r *http.Request) {
	limit, _ := strconv.Atoi(r.URL.Query().Get("limit"))
	if limit <= 0 || limit > 500 {
		limit = 200
	}
	events, err := s.Store.Events(r.Context(), r.URL.Query().Get("camera"), limit)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	writeJSON(w, http.StatusOK, events)
}

func (s *Server) handleListEvidence(w http.ResponseWriter, r *http.Request) {
	list, err := s.Store.EvidenceList(r.Context())
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	writeJSON(w, http.StatusOK, list)
}

func (s *Server) handleEvidenceFile(w http.ResponseWriter, r *http.Request) {
	ev, err := s.Store.EvidenceByID(r.Context(), r.PathValue("id"))
	if err != nil {
		writeError(w, http.StatusNotFound, "evidence not found")
		return
	}
	f, err := os.Open(filepath.Join(s.evidenceDir(), filepath.Base(ev.File)))
	if err != nil {
		writeError(w, http.StatusNotFound, "evidence file missing")
		return
	}
	defer f.Close()
	info, _ := f.Stat()
	s.audit(r, "Evidence", "Downloaded evidence", ev.CaseID)
	w.Header().Set("Content-Type", "video/mp4")
	w.Header().Set("Content-Disposition", `attachment; filename="`+ev.CaseID+`.mp4"`)
	w.Header().Set("X-Content-SHA256", ev.SHA256)
	http.ServeContent(w, r, ev.CaseID+".mp4", info.ModTime(), f)
}

func lower(s string) string {
	b := []byte(s)
	for i, c := range b {
		if c >= 'A' && c <= 'Z' {
			b[i] = c + 32
		}
	}
	return string(b)
}
