package server

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"

	"sentinel-linux/internal/ai"
	"sentinel-linux/internal/detect"
	"sentinel-linux/internal/store"
)

// Alert modes (cameras.alert_on).
const (
	alertAuto     = 0
	alertMotion   = 1
	alertObjects  = 2 // people & vehicles
	alertPeople   = 3
	vehicleMemory = 15 * time.Minute
)

// alertMode resolves "auto": people & vehicles when the detector is
// installed, else any motion.
func (s *Server) alertMode(c *store.Camera) int {
	if c.AlertOn != alertAuto {
		return c.AlertOn
	}
	if s.Detect != nil && s.Detect.Objects != nil {
		return alertObjects
	}
	return alertMotion
}

type seenBox struct {
	box  [4]float64
	last time.Time
}

// stationaryVehicles drops vehicles parked where one was already seen in the
// last 15 minutes, so a parked car doesn't fire every time someone walks by.
func (st *detectState) movingVehicles(cameraID string, objs []detect.Object, now time.Time) []detect.Object {
	st.mu.Lock()
	defer st.mu.Unlock()
	if st.vehicles == nil {
		st.vehicles = map[string][]seenBox{}
	}
	seen := st.vehicles[cameraID][:0]
	for _, b := range st.vehicles[cameraID] {
		if now.Sub(b.last) < vehicleMemory {
			seen = append(seen, b)
		}
	}
	var moving []detect.Object
	for _, o := range objs {
		matched := false
		for i := range seen {
			if detect.IoU(seen[i].box, o.Box) >= 0.6 {
				seen[i].last, seen[i].box, matched = now, o.Box, true
				break
			}
		}
		if !matched {
			seen = append(seen, seenBox{box: o.Box, last: now})
			moving = append(moving, o)
		}
	}
	st.vehicles[cameraID] = seen
	return moving
}

// episode applies the motion episode rule per camera+kind: a new event after
// 30 s without that kind, or once a minute while it continues. Returns
// whether to record an event and the alarm merge boundary.
func (st *detectState) episode(key string, at time.Time) (bool, time.Time) {
	st.mu.Lock()
	defer st.mu.Unlock()
	if st.lastMotion == nil {
		st.lastMotion, st.lastEvent = map[string]time.Time{}, map[string]time.Time{}
	}
	prevSeen, prevEvent := st.lastMotion[key], st.lastEvent[key]
	st.lastMotion[key] = at
	newEpisode := at.Sub(prevSeen) >= motionQuiet
	if !newEpisode && at.Sub(prevEvent) < motionRepeat {
		return false, time.Time{}
	}
	st.lastEvent[key] = at
	mergeSince := at.Add(time.Second)
	if !prevEvent.IsZero() && (!newEpisode || at.Sub(prevSeen) < alarmMergeWin) {
		mergeSince = prevEvent
	}
	return true, mergeSince
}

// OnObjects handles one detection pass (frames with motion only).
func (s *Server) OnObjects(d detect.Detections) {
	ctx := s.Ctx
	cam, err := s.Store.Camera(ctx, d.CameraID)
	if err != nil {
		return
	}
	best := map[string]detect.Object{}
	var vehicles []detect.Object
	for _, o := range d.Objects {
		if o.Kind == "Vehicle" {
			vehicles = append(vehicles, o)
			continue
		}
		if b, ok := best[o.Kind]; !ok || o.Score > b.Score {
			best[o.Kind] = o
		}
	}
	for _, v := range s.detect.movingVehicles(cam.ID, vehicles, d.At) {
		if b, ok := best["Vehicle"]; !ok || v.Score > b.Score {
			best["Vehicle"] = v
		}
	}
	mode := s.alertMode(cam)
	for kind, o := range best {
		record, mergeSince := s.detect.episode(cam.ID+"|"+kind, d.At)
		if !record {
			continue
		}
		box, _ := json.Marshal(o.Box)
		ev := &store.Event{CameraID: cam.ID, Kind: kind, Label: o.Label, Score: o.Score, Box: string(box), CreatedAt: d.At.Unix()}
		if err := s.Store.AddEvent(ctx, ev); err != nil {
			slog.Error("save detection event", "err", err)
			continue
		}
		var alarm *store.Alarm
		if (kind == "Person" && (mode == alertObjects || mode == alertPeople)) || (kind == "Vehicle" && mode == alertObjects) {
			title, severity := "Person detected", "Critical"
			if kind == "Vehicle" {
				title, severity = "Vehicle detected", "Warning"
			}
			a, isNew, err := s.Store.RaiseAlarm(ctx, store.AlarmInput{
				CameraID: cam.ID, CameraName: cam.Name, Kind: kind, Title: title, Severity: severity,
				Detail:  fmt.Sprintf("%s detected a %s at %s.", cam.Name, strings.ToLower(o.Label), d.At.Format("3:04:05 PM")),
				EventID: ev.ID, At: d.At, MergeSince: mergeSince, Origin: "Automatically generated by video analytics",
			})
			if err == nil {
				alarm = a
				_ = s.Store.SetEventAlarm(ctx, ev.ID, a.ID)
				if isNew {
					slog.Info("detection alarm", "camera", cam.Name, "kind", kind, "label", o.Label, "score", o.Score)
				}
			}
		}
		var detected []byte
		if d.Frame != nil {
			detected, _ = detect.FrameJPEG(d.Frame, d.ContentW, d.ContentH, [][4]float64{o.Box})
		}
		go s.finishDetection(cam, ev, alarm, detected)
	}
}

// finishDetection grabs the snapshot frames and, when AI is on, asks Claude
// for a description that is stored on the event and copied onto the alarm.
//
// The thumbnail is the analyzed frame itself with the detection outlined —
// a snapshot grabbed afterwards often misses a person who's walking.
func (s *Server) finishDetection(cam *store.Camera, ev *store.Event, alarm *store.Alarm, detected []byte) {
	ctx := s.Ctx
	if err := os.MkdirAll(s.eventsDir(), 0o750); err != nil {
		return
	}
	thumb := ev.ID + ".jpg"
	var jpegs [][]byte
	if detected != nil && os.WriteFile(filepath.Join(s.eventsDir(), thumb), detected, 0o640) == nil {
		_ = s.Store.SetEventThumbnail(ctx, ev.ID, thumb)
		jpegs = append(jpegs, detected)
	}
	describe := (ev.Kind == "Person" || ev.Kind == "Vehicle") && s.aiReady()
	if !s.Detect.Available() || (!describe && jpegs != nil) {
		return
	}
	// Higher-resolution follow-up frames: for the AI (what happens next) and
	// as the thumbnail if the analyzed frame wasn't available.
	n := 1
	if describe {
		n = 2
	}
	url := fmt.Sprintf("rtsp://127.0.0.1:%d/%s", s.Media.Ports.RTSP, s.Media.LivePath(cam.ID))
	frames, err := s.Detect.SnapshotFrames(ctx, url, s.eventsDir(), ev.ID, n)
	if err == nil {
		defer func() {
			for _, f := range frames {
				_ = os.Remove(f)
			}
		}()
		for _, f := range frames {
			if b, err := os.ReadFile(f); err == nil {
				if jpegs == nil {
					_ = os.WriteFile(filepath.Join(s.eventsDir(), thumb), b, 0o640)
					_ = s.Store.SetEventThumbnail(ctx, ev.ID, thumb)
				}
				jpegs = append(jpegs, b)
			}
		}
	}
	if !describe || len(jpegs) == 0 || !s.aiTakeBudget() {
		return
	}
	client, err := s.aiClient()
	if err != nil {
		return
	}
	actx, cancel := context.WithTimeout(ctx, 60*time.Second)
	defer cancel()
	a, err := client.AnalyzeScene(actx, jpegs, ev.Kind)
	if err != nil {
		s.setAIError(err)
		slog.Warn("AI description failed", "camera", cam.Name, "err", err)
		return
	}
	s.setAIError(nil)
	_ = s.Store.SetEventAnalysis(ctx, ev.ID, a.Description, a.Threat, a.Anomaly, a.Reason, strings.Join(a.Tags, ", "))
	if alarm != nil {
		detail := cam.Name + ": " + a.Description
		severity := ""
		if a.Threat == "elevated" || a.Threat == "high" {
			severity = "Critical"
			if a.Reason != "" {
				detail += " (" + a.Threat + " threat: " + a.Reason + ")"
			}
		}
		_ = s.Store.UpdateAlarmDetail(ctx, alarm.ID, detail, severity)
	}
}

// MARK: - AI settings (bring your own Anthropic key)

const (
	aiEnabledSetting = "ai_enabled"
	aiKeySetting     = "ai_key" // sealed with install.key
	aiLimitSetting   = "ai_daily_limit"
	aiDefaultLimit   = 300
)

type aiState struct {
	mu        sync.Mutex
	key       string
	client    *ai.Client
	day       string
	used      int
	lastError string
}

func (s *Server) aiKey() string {
	sealed := s.Store.Setting(s.Ctx, aiKeySetting, "")
	if sealed == "" {
		return ""
	}
	key, err := s.Store.Unseal(sealed)
	if err != nil {
		return ""
	}
	return key
}

func (s *Server) aiReady() bool {
	return s.Store.Setting(s.Ctx, aiEnabledSetting, "off") == "on" && s.aiKey() != ""
}

func (s *Server) aiClient() (*ai.Client, error) {
	key := s.aiKey()
	if key == "" {
		return nil, ai.ErrNoKey
	}
	s.ai.mu.Lock()
	defer s.ai.mu.Unlock()
	if s.ai.client == nil || s.ai.key != key {
		s.ai.client, s.ai.key = ai.New(key, s.AIOptions...), key
	}
	return s.ai.client, nil
}

func (s *Server) aiLimit() int {
	n, err := strconv.Atoi(s.Store.Setting(s.Ctx, aiLimitSetting, strconv.Itoa(aiDefaultLimit)))
	if err != nil || n < 0 {
		return aiDefaultLimit
	}
	return n
}

// aiTakeBudget counts one description against the daily cap (a runaway camera
// must not run up the operator's Anthropic bill).
func (s *Server) aiTakeBudget() bool {
	limit := s.aiLimit()
	s.ai.mu.Lock()
	defer s.ai.mu.Unlock()
	today := time.Now().Format("2006-01-02")
	if s.ai.day != today {
		s.ai.day, s.ai.used = today, 0
	}
	if s.ai.used >= limit {
		return false
	}
	s.ai.used++
	return true
}

func (s *Server) setAIError(err error) {
	s.ai.mu.Lock()
	defer s.ai.mu.Unlock()
	if err == nil {
		s.ai.lastError = ""
	} else {
		s.ai.lastError = err.Error()
	}
}

func (s *Server) aiStatus() map[string]any {
	s.ai.mu.Lock()
	used, lastErr := s.ai.used, s.ai.lastError
	if s.ai.day != time.Now().Format("2006-01-02") {
		used = 0
	}
	s.ai.mu.Unlock()
	return map[string]any{
		"enabled":     s.Store.Setting(s.Ctx, aiEnabledSetting, "off") == "on",
		"hasKey":      s.aiKey() != "",
		"dailyLimit":  s.aiLimit(),
		"usedToday":   used,
		"lastError":   lastErr,
		"detector":    s.Detect != nil && s.Detect.Objects != nil,
		"visionModel": ai.VisionModel,
		"searchModel": ai.TextModel,
	}
}

func (s *Server) handleGetAI(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, s.aiStatus())
}

func (s *Server) handlePutAI(w http.ResponseWriter, r *http.Request) {
	var in struct {
		Enabled    *bool   `json:"enabled"`
		APIKey     *string `json:"apiKey"` // "" clears
		DailyLimit *int    `json:"dailyLimit"`
	}
	if !readJSON(w, r, &in) {
		return
	}
	ctx := r.Context()
	if in.APIKey != nil {
		key := strings.TrimSpace(*in.APIKey)
		if key == "" {
			_ = s.Store.SetSetting(ctx, aiKeySetting, "")
			s.audit(r, "AI", "Removed Anthropic API key", "")
		} else {
			vctx, cancel := context.WithTimeout(ctx, 20*time.Second)
			err := ai.Validate(vctx, key, s.AIOptions...)
			cancel()
			if err != nil {
				writeError(w, http.StatusBadRequest, err.Error())
				return
			}
			sealed, err := s.Store.Seal(key)
			if err != nil {
				writeError(w, http.StatusInternalServerError, err.Error())
				return
			}
			_ = s.Store.SetSetting(ctx, aiKeySetting, sealed)
			s.audit(r, "AI", "Saved Anthropic API key", "key ending "+tail(key, 4))
		}
	}
	if in.DailyLimit != nil {
		if *in.DailyLimit < 0 || *in.DailyLimit > 100000 {
			writeError(w, http.StatusBadRequest, "daily limit must be between 0 and 100000")
			return
		}
		_ = s.Store.SetSetting(ctx, aiLimitSetting, strconv.Itoa(*in.DailyLimit))
	}
	if in.Enabled != nil {
		val := "off"
		if *in.Enabled {
			if s.aiKey() == "" {
				writeError(w, http.StatusBadRequest, "add your Anthropic API key first")
				return
			}
			val = "on"
		}
		_ = s.Store.SetSetting(ctx, aiEnabledSetting, val)
		s.audit(r, "AI", "Turned AI "+val, "")
	}
	writeJSON(w, http.StatusOK, s.aiStatus())
}

func tail(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[len(s)-n:]
}

// aiEventLines turns events into the text models' corpus. Detection events
// (people, vehicles, animals) are what matter; plain motion is included only
// when there is nothing else.
func (s *Server) aiEventLines(ctx context.Context, from, to time.Time) ([]ai.EventLine, map[string]store.Event, error) {
	events, err := s.Store.EventsBetween(ctx, from, to, 20000)
	if err != nil {
		return nil, nil, err
	}
	names := s.cameraNames(ctx)
	byID := map[string]store.Event{}
	var lines, motion []ai.EventLine
	for _, e := range events {
		byID[e.ID] = e
		l := ai.EventLine{ID: e.ID, Time: time.Unix(e.CreatedAt, 0), Camera: names[e.CameraID], Kind: e.Kind,
			Description: e.Description, Tags: e.Tags, Threat: e.Threat}
		if l.Camera == "" {
			l.Camera = "Camera"
		}
		if e.Kind == "Motion" {
			motion = append(motion, l)
		} else {
			lines = append(lines, l)
		}
	}
	if len(lines) == 0 {
		lines = motion
	}
	return lines, byID, nil
}

func (s *Server) handleAISearch(w http.ResponseWriter, r *http.Request) {
	var in struct {
		Query string `json:"query"`
		Days  int    `json:"days"`
	}
	if !readJSON(w, r, &in) {
		return
	}
	if !s.aiReady() {
		writeError(w, http.StatusConflict, "AI is off — add your Anthropic API key and turn AI on in System → AI")
		return
	}
	if in.Days <= 0 || in.Days > 30 {
		in.Days = 7
	}
	now := time.Now()
	lines, byID, err := s.aiEventLines(r.Context(), now.Add(-time.Duration(in.Days)*24*time.Hour), now.Add(time.Minute))
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	client, err := s.aiClient()
	if err != nil {
		writeError(w, http.StatusConflict, err.Error())
		return
	}
	ctx, cancel := context.WithTimeout(r.Context(), 120*time.Second)
	defer cancel()
	answer, ids, err := client.Search(ctx, in.Query, lines, now)
	if err != nil {
		s.setAIError(err)
		writeError(w, http.StatusBadGateway, err.Error())
		return
	}
	matches := []store.Event{}
	for _, id := range ids {
		if e, ok := byID[id]; ok {
			matches = append(matches, e)
		}
	}
	s.audit(r, "AI", "Searched events", in.Query)
	writeJSON(w, http.StatusOK, map[string]any{"answer": answer, "events": matches, "searched": len(lines)})
}

func (s *Server) handleAIDigest(w http.ResponseWriter, r *http.Request) {
	var in struct {
		Period string `json:"period"` // today | 24h | yesterday
	}
	if r.ContentLength != 0 && !readJSON(w, r, &in) {
		return
	}
	if !s.aiReady() {
		writeError(w, http.StatusConflict, "AI is off — add your Anthropic API key and turn AI on in System → AI")
		return
	}
	now := time.Now()
	midnight := time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, now.Location())
	from, to, label := midnight, now.Add(time.Minute), "today"
	switch in.Period {
	case "24h":
		from, label = now.Add(-24*time.Hour), "the last 24 hours"
	case "yesterday":
		from, to, label = midnight.AddDate(0, 0, -1), midnight, "yesterday"
	}
	lines, _, err := s.aiEventLines(r.Context(), from, to)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	client, err := s.aiClient()
	if err != nil {
		writeError(w, http.StatusConflict, err.Error())
		return
	}
	ctx, cancel := context.WithTimeout(r.Context(), 120*time.Second)
	defer cancel()
	digest, err := client.Digest(ctx, label, lines)
	if err != nil {
		s.setAIError(err)
		writeError(w, http.StatusBadGateway, err.Error())
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"digest": digest, "events": len(lines), "label": label})
}
